name: Docker Build and Push Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: sanchaljustgrow
          password: dckr_pat_T7tgK2DZbSbLekJMq_hBE7li3nI

      # Build & Push Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: . # 👈 updated path
          push: true
          tags: sanchaljustgrow/angular-dockertest-frontend:latest
          platforms: linux/amd64
